modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"

[[mods]]
modId = "clairmcbridge"
version = "${version}"
displayName = "ClairMC Bridge"
description = '''
Serwerowy mod NeoForge laczacy serwer Minecraft z ekosystemem Clair przez Bridge API.
'''

[[dependencies.clairmcbridge]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.clairmcbridge]]
modId = "minecraft"
type = "required"
versionRange = "[${neoforgeMcVersion},)"
ordering = "NONE"
side = "SERVER"
